#!/usr/bin/env python3
import sys
from open_questions import QuestionGenerator
import random

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: ./ask ARTICLE.txt NUM_QUESTIONS")
        sys.exit(1)

    article_file = sys.argv[1]
    num_questions = int(sys.argv[2])

    with open(article_file, 'r') as f:
        article_txt = f.read()

    questions_generated = QuestionGenerator(article_txt).get_questions()
    for i in range(min(len(questions_generated), num_questions)):
        print(questions_generated[i])

    if len(questions_generated) < num_questions:
        for i in range(num_questions - len(questions_generated)):
            print(random.choice(questions_generated))