#!/usr/bin/env python3 -W ignore::DeprecationWarning
import sys
import io

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: ./ask ARTICLE.txt NUM_QUESTIONS")
        sys.exit(1)

    article_txt = sys.argv[1]
    num_questions = int(sys.argv[2])

    with open(article_txt, 'r', encoding='utf8') as f:
        article_txt = f.read()

    # TODO: rank the questions

    questions = []
    for i in range(num_questions):
        question = ""
        questions.append(question)

    for i in range(num_questions):
        print(questions[i])
