#!/usr/bin/env python3
import sys
from open_questions import QuestionGenerator
import random

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: ./ask ARTICLE.txt NUM_QUESTIONS")
        sys.exit(1)

    article_file = sys.argv[1]
    num_questions = int(sys.argv[2])

    with open(article_file, 'r') as f:
        article_txt = f.read()

    # TODO: rank the questions
    qg = QuestionGenerator(article_txt)
    questions = qg.questions_only() + qg.closed_questions # open & closed qs


    #print(num_questions, questions)
    #random.shuffle(questions)
    for i in range(num_questions):
        print(questions[i])
